### ISSUE TITLE
gog-downloader:latest not available

### ISSUE THREAD

**Issue by cherryontopknife** [RikudouSage/GogDownloader#28]
I just setup a docker container running this, and `gog-downloader:latest` pulls nothing. I had to use `gog-downloader` as the image. This is a minor issue, but the docs do recommend using `:latest` in most instances.

**Comment by cherryontopknife** [comment]
Not that I can get the docker container working! A compose file would be a big help!

**Comment by RikudouSage** [comment]
I just tried `docker pull rikudousage/gog-downloader:latest` and it seems to work.

**Comment by RikudouSage** [comment]
As for compose, it's not really usable as a compose project, it doesn't run periodically in the background, it's meant more to run as a temporary container that will exit once it's done.

From the README:

`docker run --rm -it --init -v "$(pwd)/Configs:/Configs" -v "$(pwd)/Downloads:/Downloads" rikudousage/gog-downloader:latest`

This will run the help command, if you want to run `update` (or other command), you just append it:

`docker run --rm -it --init -v "$(pwd)/Configs:/Configs" -v "$(pwd)/Downloads:/Downloads" rikudousage/gog-downloader:latest update`

or

`docker run --rm -it --init -v "$(pwd)/Configs:/Configs" -v "$(pwd)/Downloads:/Downloads" rikudousage/gog-downloader:latest download`

---

It's a really long command, that's why I recommend aliasing it, you run this command once:

alias gog-downloader='docker run --rm -it --init -v $(pwd)/Configs:/Configs -v $(pwd)/Downloads:/Downloads rikudousage/gog-downloader:latest'

And afterwards you can just use `gog-downloader` in the terminal. If you're on Windows, I'm not aware of anything similar to the `alias` command, so you'll have to type it out full.

---

I guess you could use something like:

```yaml
services:
  login:
    image: rikudousage/gog-downloader:latest
    init: true
    stdin_open: true
    tty: true
    volumes:
      - ./Configs:/Configs
      - ./Downloads:/Downloads
    command: code-login
  update:
    image: rikudousage/gog-downloader:latest
    init: true
    volumes:
      - ./Configs:/Configs
      - ./Downloads:/Downloads
    command: update
  download:
    image: rikudousage/gog-downloader:latest
    init: true
    volumes:
      - ./Configs:/Configs
      - ./Downloads:/Downloads
    command: download --language cz --language-fallback-english
```

And then use it like `docker compose up update` or `docker compose up download`, but it feels weird to me. Note that the login service needs some fixing, didn't really manage to make it work, but I haven't tried much.
