### ISSUE TITLE
Some Linux  game installers are being downloaded and appended to existing files.

### ISSUE THREAD

**Issue by cormacj** [RikudouSage/GogDownloader#81]
On GOG linux game installers are typically .sh files, and unlike windows this single .sh file contains everything needed to install the whole game.

I have a few installers that are 3GB+ which gets downloaded each time I do an update. The download will append the downloaded .sh file to the existing .sh file, which caused one of my download directories to balloon to over 80GB for a single .sh file thats normally around 4GB.

The simple file would be to add a flag to skip downloads if the name already exists.

**Comment by RikudouSage** [comment]
There's the `--no-verify` flag - it disables verification and skips existing files.

**Comment by agowa** [comment]
This bug also applies to macos files.

Example downloads `[Amnesia: A Machine For Pigs] Amnesia: A Machine For Pigs (mac, en)` and `[Anomaly Defenders] Anomaly Defenders (mac, en)`

Steps to reproduce:
1. `docker compose run --rm gog-downloader code-login` and login to an account that has at least one of these two games.
2. `docker compose run gog-downloader download --extras --skip-existing-extras`
3. wait until it completes.
4. `docker compose run gog-downloader download --extras --skip-existing-extras` run it again.
5. Observe that the .dmg file is double the size as it should be.

Edit: The docker-compose.yml file I used:
```
version: "3.8"

services:
  gog-downloader:
    image: rikudousage/gog-downloader:latest
    container_name: gog-downloader
    stdin_open: true   # equivalent to -i
    tty: true          # equivalent to -t
    init: true         # equivalent to --init
    volumes:
      - ./Configs:/Configs
      - ./Downloads:/Downloads
    restart: "no"      # equivalent behavior to --rm for one-off runs
```
